/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CompanyRegistry {
  export type CompanyStruct = {
    name: string;
    trustAnchor: AddressLike;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type CompanyStructOutput = [
    name: string,
    trustAnchor: string,
    active: boolean,
    registeredAt: bigint
  ] & {
    name: string;
    trustAnchor: string;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface CompanyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "companies"
      | "companyAdmins"
      | "createCompany"
      | "deactivateCompany"
      | "didRegistry"
      | "getAdmins"
      | "getCompany"
      | "isAdmin"
      | "isCompanyAdmin"
      | "removeAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminRemoved"
      | "CompanyDeactivated"
      | "CompanyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "companies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "companyAdmins",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCompany",
    values: [AddressLike, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "didRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAdmins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompany",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompanyAdmin",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "companyAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "didRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCompany", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCompanyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [
    companyDID: AddressLike,
    admin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyDID: string,
    admin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyDID: string;
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [
    companyDID: AddressLike,
    admin: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyDID: string,
    admin: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyDID: string;
    admin: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyDeactivatedEvent {
  export type InputTuple = [companyDID: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [companyDID: string, timestamp: bigint];
  export interface OutputObject {
    companyDID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyRegisteredEvent {
  export type InputTuple = [
    companyDID: AddressLike,
    name: string,
    trustAnchor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    companyDID: string,
    name: string,
    trustAnchor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    companyDID: string;
    name: string;
    trustAnchor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CompanyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CompanyRegistry;
  waitForDeployment(): Promise<this>;

  interface: CompanyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;

  companies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        trustAnchor: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  companyAdmins: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  createCompany: TypedContractMethod<
    [companyDID: AddressLike, name: string, trustAnchor: AddressLike],
    [void],
    "nonpayable"
  >;

  deactivateCompany: TypedContractMethod<
    [companyDID: AddressLike],
    [void],
    "nonpayable"
  >;

  didRegistry: TypedContractMethod<[], [string], "view">;

  getAdmins: TypedContractMethod<[companyDID: AddressLike], [string[]], "view">;

  getCompany: TypedContractMethod<
    [companyDID: AddressLike],
    [CompanyRegistry.CompanyStructOutput],
    "view"
  >;

  isAdmin: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isCompanyAdmin: TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [boolean],
    "view"
  >;

  removeAdmin: TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "companies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        trustAnchor: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "companyAdmins"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCompany"
  ): TypedContractMethod<
    [companyDID: AddressLike, name: string, trustAnchor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateCompany"
  ): TypedContractMethod<[companyDID: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "didRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAdmins"
  ): TypedContractMethod<[companyDID: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCompany"
  ): TypedContractMethod<
    [companyDID: AddressLike],
    [CompanyRegistry.CompanyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCompanyAdmin"
  ): TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyDeactivated"
  ): TypedContractEvent<
    CompanyDeactivatedEvent.InputTuple,
    CompanyDeactivatedEvent.OutputTuple,
    CompanyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyRegistered"
  ): TypedContractEvent<
    CompanyRegisteredEvent.InputTuple,
    CompanyRegisteredEvent.OutputTuple,
    CompanyRegisteredEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address,address,uint256)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address,address,uint256)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "CompanyDeactivated(address,uint256)": TypedContractEvent<
      CompanyDeactivatedEvent.InputTuple,
      CompanyDeactivatedEvent.OutputTuple,
      CompanyDeactivatedEvent.OutputObject
    >;
    CompanyDeactivated: TypedContractEvent<
      CompanyDeactivatedEvent.InputTuple,
      CompanyDeactivatedEvent.OutputTuple,
      CompanyDeactivatedEvent.OutputObject
    >;

    "CompanyRegistered(address,string,address,uint256)": TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
    CompanyRegistered: TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
  };
}
