/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompanyRegistry } from "./CompanyRegistry";
export type { DIDRegistry } from "./DIDRegistry";
export type { MockTrustAnchor } from "./MockTrustAnchor";
export * as factories from "./factories";
export { CompanyRegistry__factory } from "./factories/CompanyRegistry__factory";
export { DIDRegistry__factory } from "./factories/DIDRegistry__factory";
export { MockTrustAnchor__factory } from "./factories/MockTrustAnchor__factory";
