/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockTrustAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCompanyAdmin"
      | "companyRegistryAddress"
      | "didRegistryAddress"
      | "grantServiceAdmin"
      | "revokeDelegate"
      | "setCompanyAttribute"
      | "transferCompanyOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AdminGranted"): EventFragment;

  encodeFunctionData(
    functionFragment: "addCompanyAdmin",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "companyRegistryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "didRegistryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantServiceAdmin",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegate",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompanyAttribute",
    values: [AddressLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferCompanyOwnership",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCompanyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "didRegistryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantServiceAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompanyAttribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCompanyOwnership",
    data: BytesLike
  ): Result;
}

export namespace AdminGrantedEvent {
  export type InputTuple = [
    companyDID: AddressLike,
    admin: AddressLike,
    role: string,
    validity: BigNumberish
  ];
  export type OutputTuple = [
    companyDID: string,
    admin: string,
    role: string,
    validity: bigint
  ];
  export interface OutputObject {
    companyDID: string;
    admin: string;
    role: string;
    validity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockTrustAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): MockTrustAnchor;
  waitForDeployment(): Promise<this>;

  interface: MockTrustAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCompanyAdmin: TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike, validity: BigNumberish],
    [void],
    "nonpayable"
  >;

  companyRegistryAddress: TypedContractMethod<[], [string], "view">;

  didRegistryAddress: TypedContractMethod<[], [string], "view">;

  grantServiceAdmin: TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike, validity: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeDelegate: TypedContractMethod<
    [companyDID: AddressLike, delegateType: BytesLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  setCompanyAttribute: TypedContractMethod<
    [
      companyDID: AddressLike,
      name: BytesLike,
      value: BytesLike,
      validity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferCompanyOwnership: TypedContractMethod<
    [companyDID: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCompanyAdmin"
  ): TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike, validity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "companyRegistryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "didRegistryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantServiceAdmin"
  ): TypedContractMethod<
    [companyDID: AddressLike, admin: AddressLike, validity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeDelegate"
  ): TypedContractMethod<
    [companyDID: AddressLike, delegateType: BytesLike, delegate: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCompanyAttribute"
  ): TypedContractMethod<
    [
      companyDID: AddressLike,
      name: BytesLike,
      value: BytesLike,
      validity: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferCompanyOwnership"
  ): TypedContractMethod<
    [companyDID: AddressLike, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminGranted"
  ): TypedContractEvent<
    AdminGrantedEvent.InputTuple,
    AdminGrantedEvent.OutputTuple,
    AdminGrantedEvent.OutputObject
  >;

  filters: {
    "AdminGranted(address,address,string,uint256)": TypedContractEvent<
      AdminGrantedEvent.InputTuple,
      AdminGrantedEvent.OutputTuple,
      AdminGrantedEvent.OutputObject
    >;
    AdminGranted: TypedContractEvent<
      AdminGrantedEvent.InputTuple,
      AdminGrantedEvent.OutputTuple,
      AdminGrantedEvent.OutputObject
    >;
  };
}
