/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CompanyRegistry__factory } from "./CompanyRegistry__factory";
export { DIDRegistry__factory } from "./DIDRegistry__factory";
export { MockTrustAnchor__factory } from "./MockTrustAnchor__factory";
